name: Build docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_REGISTRY }}
          username: ${{ secrets.AZURE_APP_ID }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Build ID
        run: echo "id=$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.AZURE_REGISTRY }}/payangel-api-docs:latest
            ${{ secrets.AZURE_REGISTRY }}/payangel-api-docs:${{ steps.build-id.outputs.id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

# - name: Set up kubectl
#   uses: azure/k8s-set-context@v3
#   with:
#     kubeconfig: ${{ secrets.KUBE_CONFIG }}
#
# - name: Deploy to Kubernetes
#   run: |
#     # Replace placeholder in deployment.yaml
#     sed -i "s|\${CONTAINER_REGISTRY}|${{ env.CONTAINER_REGISTRY }}|g" kubernetes/deployment.yaml
#     sed -i "s|\${IMAGE_TAG}|${{ steps.build-id.outputs.id }}|g" kubernetes/deployment.yaml
#
#     # Apply Kubernetes manifests
#     kubectl apply -f kubernetes/configmap.yaml -n ${{ env.KUBE_NAMESPACE }}
#     kubectl apply -f kubernetes/deployment.yaml -n ${{ env.KUBE_NAMESPACE }}
#     kubectl apply -f kubernetes/service.yaml -n ${{ env.KUBE_NAMESPACE }}
#
#     # Wait for deployment to roll out
#     kubectl rollout status deployment/payangel-api-docs -n ${{ env.KUBE_NAMESPACE }} --timeout=300s
